EcoKitchen_backend/EcoKitchen/urls.py
from django.conf.urls import url

from . import views
app_name = 'EcoKitchen'

urlpatterns = [
    url(r'^signin', views.signInUser),
    url(r'^signup', views.signUpUser),
    url(r'^location/(?P<locationId>[0-9]+)$', views.getLocation),
    url(r'^location$', views.postLocation),
    url(r'^locations$', views.getAllLocations),
    url(r'^feedback$', views.addFeedback),
    url(r'^referEntrepreneur', views.createEntreprenuerReferral),
    url(r'^askQuestion$', views.askQuestion),
    url(r'^userspage/$', views.userspage, name='userspage'),
    url(r'^locationspage/$', views.locationspage, name='locationspage'),
    url(r'^feedbackpage/$', views.feedbackpage, name='feedbackpage'),
    url(r'^locationdetail/(?P<location_id>[0-9]+)/$', views.locationdetail, name='locationdetail'),
    url(r'^userdetail/(?P<user_id>[0-9]+)/$', views.userdetail, name='userdetail'),    
    url(r'^entrepreneurs/$', views.entrepreneurs, name='entrepreneurs'),
    url(r'^entredetail/(?P<entre_id>[0-9]+)/$', views.entredetail, name='entredetail'),
]

EcoKitchen_backend/EcoKitchen_backend/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf.urls import include
from rest_framework import routers

router = routers.DefaultRouter()

urlpatterns = [
    url(r'^EcoKitchen/', include('EcoKitchen.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include(router.urls)),
    url(r'api/', include('EcoKitchen.urls')),
]

EcoKitchen_backend/EcoKitchen/models.py
from django.db import models

class UserProfile(models.Model):
  name = models.CharField(max_length=30)
  address = models.CharField(max_length=250)
  email = models.EmailField(max_length=100, null=True, blank=True, default=None)
  mobile = models.CharField(max_length=30)
  password = models.CharField(max_length=30)

class Location(models.Model):
  lat = models.CharField(max_length=30)
  long = models.CharField(max_length=30)
  address = models.CharField(max_length=200)
  description = models.CharField(max_length=50)
  status = models.BooleanField()
  user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
  def __str__(self):
    return self.address

class FeedBack(models.Model):
  content = models.CharField(max_length=200)
  courtesy = models.FloatField(default=None)
  qualityOfFood =  models.FloatField(default=None)
  quantityOfFood =  models.FloatField(default=None)
  foodTaste = models.FloatField(default=None)
  cleanliness = models.FloatField(default=None)
  location = models.ForeignKey(Location, on_delete = models.CASCADE)
  user = models.ForeignKey(UserProfile, on_delete = models.CASCADE)

class ReferredPerson(models.Model):
  location = models.OneToOneField(Location, on_delete = models.CASCADE, default=None, null=True)
  name = models.CharField(max_length=200, default=None)
  phone = models.CharField(max_length=200, default=None)
  incomeRange = models.CharField(max_length=200, default=None)
  maritalStatus = models.CharField(max_length=200, default=None)
  description = models.CharField(max_length=200, default=None)
  qualification = models.CharField(max_length=200, default=None)
  user = models.ForeignKey(UserProfile, on_delete = models.CASCADE)

EcoKitchen_backend/EcoKitchen/views.py
import logging,hashlib,base64
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from rest_framework import serializers
from rest_framework.decorators import api_view, parser_classes
from rest_framework.parsers import JSONParser
from .models import UserProfile,Location,FeedBack,ReferredPerson
import logging

# Create your views here.

logging.basicConfig()
logger = logging.getLogger(__name__)

UserProfile_NAME = "name"
UserProfile_PASSWORD = "password"
UserProfile_EMAIL = "email"
UserProfile_ADDRESS = "address"
UserProfile_MOBILE = "mobile"
HASH_SALT = b'SECRET_SALT'
NUM_ITERATIONS = 10000

def post_list(self, *args, **kwargs):
  return HttpResponse('{"success":"true"}')

class LocationSerializer(serializers.Serializer):
    lat = serializers.CharField(max_length=30)
    long = serializers.CharField(max_length=30)
    id = serializers.IntegerField()
    address = serializers.CharField(max_length=200)
    description = serializers.CharField(max_length=50)
    status = serializers.BooleanField()

@api_view(['POST'])
@parser_classes((JSONParser,))
def signInUser(request):
  logger.critical(request.method)
  #logger.critical("DATA :: " + request.body)
  result = True;
  msg = None;
  userProfile = None
  response_data = {}
  if request.method == 'POST' and request.content_type == 'application/json' :
    mobile = request.data[UserProfile_MOBILE]
    password = request.data[UserProfile_PASSWORD]
    passwordHash = base64.b64encode(hashlib.pbkdf2_hmac('sha256', password, HASH_SALT, NUM_ITERATIONS))
    try :
        userProfile = UserProfile.objects.get(mobile=mobile, password=passwordHash)
    except ObjectDoesNotExist:
        logger.critical("User did not exist")
        result = False
        msg = "Wrong User Name password Combination"
    except MultipleObjectsReturned:
        logger.critical("Multiple objects returned")
        msg = "Multiple objects returned"
        result = False
  else:
    msg = "Unknown ContentType or Method Name"
    result = False

  response_data['success'] = result
  response_data['message'] = msg
  if result:
    response_data['userId'] = userProfile.id
  return JsonResponse(response_data)

@api_view(['POST'])
@parser_classes((JSONParser,))
def signUpUser(request):
    #logger.critical("DATA :: " + request.body)

    result = True
    msg = None
    userProfile = None
    if request.method == 'POST' and request.content_type == 'application/json' :
        name = request.data[UserProfile_NAME]
        password = request.data[UserProfile_PASSWORD]
        #logger.critical("PAssword:: " + password)
        passwordHash = base64.b64encode(hashlib.pbkdf2_hmac('sha256', password, HASH_SALT, NUM_ITERATIONS))
        #logger.critical("PAssword hash:: " + passwordHash)
        email = request.data[UserProfile_EMAIL]
        address = request.data[UserProfile_ADDRESS]
        mobile = request.data[UserProfile_MOBILE]
        try:
            if len(email) > 0:
                existingUser = UserProfile.objects.filter(Q(email=email)|Q(mobile=mobile))
            else:
                existingUser = UserProfile.objects.filter(Q(mobile=mobile))
            if existingUser != None and existingUser.count() > 0:
                result = False
                msg = "A user is present with same email or mobile number"
            else:
                userProfile = UserProfile(name=name, password=passwordHash,
                                  email=email, address=address, mobile=mobile)
                userProfile.save()
        except Exception as e:
            logger.critical("Cannot insert succesfully")
            logger.critical(e)
            result = False
            msg = "DB insertion error"
    else:
        result = False
        msg = "Unknown ContentType or Method"

    response_data = {}
    response_data['success'] = result
    response_data['message'] = msg
    if result:
        response_data['userId'] = userProfile.id
    return JsonResponse(response_data)

def getLocation(request, locationId):
    logger.critical(request.method)
    #logger.critical("DATA :: " + request.body)
    result = True
    msg = None
    location = None
    try :
        location = Location.objects.get(id=locationId)
    except ObjectDoesNotExist:
        logger.critical("Location does not exist")
        result = False
        msg = "Location does not exist"
    except MultipleObjectsReturned:
        logger.critical("Multiple objects returned")
        msg = "Multiple objects returned"
        result = False
    response_data = {}
    if result:
        response_data = {}
        response_data['status'] = location.status
        response_data['description'] = location.description
        response_data['address'] = location.address
        response_data['userId'] = location.user.id
        response_data['lat'] = location.lat
        response_data['long'] = location.long
        response_data['id'] = location.id
        return JsonResponse(response_data)
    else:
        response_data['success'] = False
        response_data['message'] = msg
    return JsonResponse(response_data)

@api_view(['POST'])
@parser_classes((JSONParser,))
def postLocation(request):
    result = True
    msg = None
    location = None
    if request.method == 'POST' and request.content_type == 'application/json' :
        description = request.data['description']
        address = request.data['address']
        userId = request.data['userId']
        lat = str(request.data['lat'])
        long = str(request.data['long'])
        status = False
        try:
            existingLocation = Location.objects.filter(Q(lat=lat) & Q(long=long))
            userReferenced = None
            if existingLocation != None and existingLocation.count() > 0:
                result = False
                msg = "A Location is present with same Latitude and Longitude"
            else:
                try :
                    userReferenced = UserProfile.objects.get(id=userId)
                except ObjectDoesNotExist:
                    result = False
                    msg = "A User Id specified for location doesn't exist"
                location = Location(lat=lat, long=long,
                          address=address, description=description, status=status, user=userReferenced)
                location.save()
        except Exception as ex:
            #logger.critical("Cannot insert succesfully:" + str(ex))
            result = False
            msg = "DB insertion error"
    else:
        result = False
        msg = "Unknown ContentType or Method"

    response_data = {}
    response_data['success'] = result
    response_data['message'] = msg
    if result:
        response_data['locationId'] = location.id
    return JsonResponse(response_data)

@api_view(['GET', 'POST'])
@parser_classes((JSONParser,))
def getAllLocations(request):
    locationList = Location.objects.all()
    if locationList != None and locationList.count() > 0:
        locationJson = LocationSerializer(locationList, many=True)
        return JsonResponse(locationJson.data, safe=False)
    else:
        return JsonResponse({})

@api_view(['POST'])
@parser_classes((JSONParser,))
def addFeedback(request):
    result = True
    msg = None
    feedback = None
    if request.method == 'POST' and request.content_type == 'application/json' :
        content = request.data['content']
        locationId = request.data['locationId']
        userId = request.data['userId']
        courtesy = request.data['courtesy']
        cleanliness = request.data['cleanliness']
        qualityOfFood =  request.data['qualityOfFood']
        quantityOfFood =  request.data['quantityOfFood']
        foodTaste = request.data['foodTaste']
        try:
            existingLocations = Location.objects.filter(id=locationId)
            existingUsers = UserProfile.objects.filter(id=userId)
            if existingLocations != None and existingLocations.count() > 0 and existingUsers != None and existingUsers.count() > 0:
                location = existingLocations.first()
                user = existingUsers.first()
                feedback = FeedBack(content=content, user=user, location=location, courtesy= courtesy, qualityOfFood = qualityOfFood,
                                    quantityOfFood = quantityOfFood, foodTaste = foodTaste, cleanliness= cleanliness)
                feedback.save()
            else:
                result = False
                msg = "Invalid Location or User!"

        except Exception as ex:
            logger.critical("Cannot insert succesfully:" + str(ex))
            result = False
            msg = "DB insertion error"
    else:
        result = False
        msg = "Unknown ContentType or Method"

    response_data = {}
    response_data['success'] = result
    response_data['message'] = msg
    if result:
        response_data['feedbackId'] = feedback.id
    return JsonResponse(response_data)

@api_view(['POST'])
@parser_classes((JSONParser,))
def createEntreprenuerReferral(request):
    result = True
    msg = None
    referredPerson = None
    if request.method == 'POST' and request.content_type == 'application/json' :
        name = request.data['name']
        phone = request.data['phone']
        incomeRange = request.data['incomeRange']
        maritalStatus = request.data['maritalStatus']
        description =  request.data['description']
        qualification = request.data['qualification']
        userId =  request.data['userId']
        try:
            existingUsers = UserProfile.objects.filter(id=userId)
            if existingUsers != None and existingUsers.count() > 0:
                user = existingUsers.first()

EcoKitchen_backend/EcoKitchen/templates/EcoKitchen/entrepreneurs.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>Users list page</title>
		<meta name="description" content="Locations:of users" />
		<meta name="keywords" content="Locations of users" />
		<meta name="author" content="Codrops" />
		<link rel="shortcut icon" href="../favicon.ico">
		<link rel="stylesheet" type="text/css" href="{% static 'EcoKitchen/normalize.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'EcoKitchen/demo.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'EcoKitchen/component.css' %}" />
		<!--[if IE]>
  		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>
		<div class="container">
			<!-- Top Navigation -->
			<div class="codrops-top clearfix">
				
				
			</div>
			<header>
				<h1>List of referred <em>Entrepreneurs</em> <span>Validation of users</span></h1>	
				<nav class="codrops-demos">
					<a href="../feedbackpage">Feedback</a>
					<a href="../locationspage" title="Locations of Entrepreneurs">Locations of Entrepreneurs</a>
					<a href="../userspage">List of users</a>
					<a class="current-demo" href="../entrepreneurs">List of Entrepreneurs</a>
					
					
					
				</nav>
			</header>
			<div class="component">
				<h2>Entrepreneurs:</h2>
				<p>List of entrepreneurs who are enrolled</p>
				
				<table>
					<thead>
						<tr>
							<th>Referrer</th>
							<th>Name</th>
							<th>Assigned Location</th>
							<th>Phone</th>
							<th>Income Range</th>
							<th>Marital Status</th>
							<th>Description</th>
							
							
						</tr>
					</thead>
					<tbody>
						{% for entre in entre_list %}
                        <tr>
							<td align="left">{{entre.user.name}}</td>
							<td align="left"><a href="{% url 'EcoKitchen:entredetail' entre.id %}">{{entre.name}}</a></td>
							<td align="left">{{entre.location.address}}</td>
							<td align="left">{{entre.phone}}</td>
							<td align="left">{{entre.incomeRange}}</td>
							<td align="left">{{entre.maritalStatus}}</td>
							<td align="left">{{entre.description}}</td></tr>
                        {% endfor %}
					</tbody>
				</table>
				
			</div>
			
		</div><!-- /container -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-throttle-debounce/1.1/jquery.ba-throttle-debounce.min.js"></script>
		<script src="js/jquery.stickyheader.js"></script>
	</body>
</html>

EcoKitchen_backend/EcoKitchen/templates/EcoKitchen/feedbackpage.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>Users list page</title>
		<meta name="description" content="Locations:of users" />
		<meta name="keywords" content="Locations of users" />
		<meta name="author" content="Codrops" />
		<link rel="shortcut icon" href="../favicon.ico">
		<link rel="stylesheet" type="text/css" href="{% static 'EcoKitchen/normalize.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'EcoKitchen/demo.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'EcoKitchen/component.css' %}" />
		<!--[if IE]>
  		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>
		<div class="container">
			<!-- Top Navigation -->
			<div class="codrops-top clearfix">
				
				
			</div>
			<header>
				<h1>Feedback <em></em> <span>Feedback received from users</span></h1>	
				<nav class="codrops-demos">
					<a class="current-demo" href="../feedbackpage">Feedback</a>
					<a href="../locationspage" title="Locations of Entrepreneurs">Locations of Entrepreneurs</a>
					<a href="../userspage">List of users</a>
					<a href="../entrepreneurs">List of Entrepreneurs</a>
					
					
					
				</nav>
			</header>
			<div class="component">
				<h2>Feedback:</h2>
				<p>List of feedback received from users (Ratings of 5)</p>
				<table>
					<thead>
						<tr>
							<th>Person</th>
							<th>Recommendation</th>
							<th>Courtesy</th>
							<th>Quality Of Food</th>
							<th>Quantity Of Food</th>
							<th>Cleanliness</th>
							<th>Location</th>
						</tr>
					</thead>
					<tbody>
						{% for fdbk in feedback_list %}
                        <tr>
							<td align="left">{{fdbk.user.name}}</td>
							<td align="left">{{fdbk.content}}</td>
							<td align="left">{{fdbk.qualityOfFood}}</td>
							<td align="left">{{fdbk.quantityOfFood}}</td>
							<td align="left">{{fdbk.foodTaste}}</td>
							<td align="left">{{fdbk.cleanliness}}</td>
							<td align="left">{{fdbk.location.address}}</td>
						</tr>

                        {% endfor %}
					</tbody>
				</table>
				
			</div>
			
		</div><!-- /container -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-throttle-debounce/1.1/jquery.ba-throttle-debounce.min.js"></script>
		<script src="js/jquery.stickyheader.js"></script>
	</body>
</html>

EcoKitchen_backend/EcoKitchen/templates/EcoKitchen/locations.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>Locations list page</title>
		<meta name="description" content="Locations:of users" />
		<meta name="keywords" content="Locations of users" />
		<meta name="author" content="Codrops" />
		<link rel="shortcut icon" href="../favicon.ico">
		<link rel="stylesheet" type="text/css" href="{% static 'EcoKitchen/normalize.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'EcoKitchen/demo.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'EcoKitchen/component.css' %}" />
		<!--[if IE]>
  		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>
		<div class="container">
			<!-- Top Navigation -->
			<div class="codrops-top clearfix">
				
				
			</div>
			<header>
				<h1>Locations of <em>Entrepreneurs</em> <span>Validation of location</span></h1>	
				<nav class="codrops-demos">
					<a href="../feedbackpage">Feedback</a>
					<a class="current-demo" href="../locationspage">Locations of Entrepreneurs</a>
					<a href="../userspage">List of users</a>
					<a href="../entrepreneurs">List of Entrepreneurs</a>
					
					
					
				</nav>
			</header>
			<div class="component">
				<h2>Locations:</h2>
				<p>List of suggested locations for the kiosk</p>
				
				<table>
					<thead>
						<tr>
							<th>User profile</th>
							<th>Location</th>
							<th>Latitude</th>
							<th>Longitude</th>
							<th>Status</th>
							<th>Description</th>
						</tr>
					</thead>
					<tbody>
						{% for location in locations_list %}
                        <tr><td align="left">{{location.user.name}}</td><td align="left"><a href="{% url 'EcoKitchen:locationdetail' location.id %}">{{location.address}}</a></td><td align="left">{{location.lat}}</td><td align="left">{{location.long}}</td><td align="left">{{location.status}}</td><td align="left">{{location.description}}</td></tr>

                        {% endfor %}
					</tbody>
				</table>
				
			</div>
			
		</div><!-- /container -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-throttle-debounce/1.1/jquery.ba-throttle-debounce.min.js"></script>
		<script src="js/jquery.stickyheader.js"></script>
	</body>
</html>

EcoKitchen_backend/EcoKitchen/templates/EcoKitchen/userdetail.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>Users list page</title>
		<meta name="description" content="Locations:of users" />
		<meta name="keywords" content="Locations of users" />
		<meta name="author" content="Codrops" />
		<link rel="shortcut icon" href="../favicon.ico">
		<link rel="stylesheet" type="text/css" href="{% static 'EcoKitchen/normalize.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'EcoKitchen/demo.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'EcoKitchen/component.css' %}" />
		<!--[if IE]>
  		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>
		<div class="container">
			<!-- Top Navigation -->
			<div class="codrops-top clearfix">
				
				
			</div>
			<header>
				<h1>Locations of <em>Entrepreneurs</em> <span>Validation of users</span></h1>	
				<nav class="codrops-demos">
					<a href="../feedbackpage">Feedback</a>
					<a href="../locationspage" title="Locations of Entrepreneurs">Locations of Entrepreneurs</a>
					<a class="current-demo" href="../userspage">List of users</a>
					
					
					
				</nav>
			</header>
			<div class="component">
				<h2>Entrepreneurs</h2>
				<p>List of entrepreneurs who are enrolled at present</p>
				
				<table>
					<thead>
						<tr>
							<th>Name</th>
							<th>Location</th>
							<th>Latitude</th>
							<th>Longitude</th>
							<th>Status</th>
							<th>Description</th>
						</tr>
					</thead>
					<tbody>
						{% for usr in users_list %}
                        <tr><td align="left"><a href="{% url 'EcoKitchen:userdetail' usr.id %}">{{usr.name}}</a></td><td align="left">{{usr.address}}</td><td align="left">{{usr.email}}</td><td align="left">{{usr.mobile}}</td></tr>

                        {% endfor %}
					</tbody>
				</table>
				
			</div>
			
		</div><!-- /container -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-throttle-debounce/1.1/jquery.ba-throttle-debounce.min.js"></script>
		<script src="js/jquery.stickyheader.js"></script>
	</body>
</html>

EcoKitchen_backend/EcoKitchen/templates/EcoKitchen/users.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>Users list page</title>
		<meta name="description" content="Locations:of users" />
		<meta name="keywords" content="Locations of users" />
		<meta name="author" content="Codrops" />
		<link rel="shortcut icon" href="../favicon.ico">
		<link rel="stylesheet" type="text/css" href="{% static 'EcoKitchen/normalize.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'EcoKitchen/demo.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'EcoKitchen/component.css' %}" />
		<!--[if IE]>
  		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>
		<div class="container">
			<!-- Top Navigation -->
			<div class="codrops-top clearfix">
				
				
			</div>
			<header>
				<h1>List of <em>Users</em> <span>Users of the app</span></h1>	
				<nav class="codrops-demos">
					<a href="../feedbackpage">Feedback</a>
					<a href="../locationspage" title="Locations of Entrepreneurs">Locations of Entrepreneurs</a>
					<a class="current-demo" href="../userspage">List of users</a>
					<a href="../entrepreneurs">List of Entrepreneurs</a>
					
					
					
				</nav>
			</header>
			<div class="component">
				<h2>Users:</h2>
				<p>List of users who are enrolled</p>
				
				<table>
					<thead>
						<tr>
							<th>Name</th>
							<th>Address</th>
							<th>Email</th>
							<th>Mobile</th>
							
							
						</tr>
					</thead>
					<tbody>
						{% for usr in users_list %}
                        <tr><td align="left"><a href="{% url 'EcoKitchen:userdetail' usr.id %}">{{usr.name}}</a></td><td align="left">{{usr.address}}</td><td align="left">{{usr.email}}</td><td align="left">{{usr.mobile}}</td></tr>

                        {% endfor %}
					</tbody>
				</table>
				
			</div>
			
		</div><!-- /container -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-throttle-debounce/1.1/jquery.ba-throttle-debounce.min.js"></script>
		<script src="js/jquery.stickyheader.js"></script>
	</body>
</html>